### ISSUE TITLE
Can't link colours in my prefab

### ISSUE THREAD

**Issue by MattQuick** [letharqic/Colorlink#1]
I right click the property, click Link Colour, and select a colour. But it doesn't actually apply. I'm trying this on an Image component but it also doesn't work on any other colour property. It works if I don't do it in prefab mode, but then it's not applied to my prefab despite applying the changes

**Comment by letharqic** [comment]
Hi! Thank you for brining this to my attention. This seems to be an unfortunate problem on Unity end of things, where objects in the Prefab Stage just straight up [don't get a proper GUID](https://forum.unity.com/threads/prefabstage-globalobjectid.1295646/), and the tool relies on GUID to find the property and change it. Can't see any immediate solutions for it, but will try and find a workaround.

**Comment by MattQuick** [comment]
> Hi! Thank you for brining this to my attention. This seems to be an unfortunate problem on Unity end of things, where objects in the Prefab Stage just straight up [don't get a proper GUID](https://forum.unity.com/threads/prefabstage-globalobjectid.1295646/), which Colorlink needs to find the property. Can't see any immediate solutions for it, but will try and find a workaround.

Appreciate the reply! This seems like a great asset. Fingers crossed you can figure something out

**Comment by letharqic** [comment]
Good news, I think I found a hacky solution for it. I'll push a commit very soon, please let me know how it went on your end (updating the tool won't break any existing links).

**Comment by letharqic** [comment]
Okay, have been testing it for a bit and there are still some problems (mainly Prefab Stage not always updating to show changes). Working on it!

**Comment by letharqic** [comment]
Pushed fixes for those as well. Will be waiting for your feedback to close the issue :)
