### ISSUE TITLE
Can't paste Color Links in prefabs

### ISSUE THREAD

**Issue by MattQuick** [letharqic/Colorlink#2]
Sorry to make another issue so soon after the last haha. It's basically the same issue is last time but with pasting color links between ui elements. If you need more info, let me know

**Comment by letharqic** [comment]
No worries, that was a silly oversight on my side. Should work properly now!

**Comment by MattQuick** [comment]
It works, but only on one object at a time. Is that intended?

**Comment by letharqic** [comment]
Not sure what do you mean by this, can you elaborate please?

**Comment by MattQuick** [comment]
Say I want to copy the color links for a button. If I select 5 buttons and paste the color link, it only pastes to one.

**Comment by letharqic** [comment]
Hm, that wouldn't work, yeah. Now that you mentioned it, you also can't manually link a property for multiple selected objects. I'll see what can be done (probably tomorrow) about it.

**Comment by MattQuick** [comment]
Cool, wasn't sure if it were a bug or not. Appreciate the quick responses!

**Comment by letharqic** [comment]
Should be working now! Thank you too for helping making the tool better C:

**Comment by MattQuick** [comment]
It's still only applying to one at a time 😅

**Comment by letharqic** [comment]
Guess I misunderstood your problem and fixed a different big bug instead lol. Nooooow I think it works though...

**Comment by MattQuick** [comment]
Sweet, pasting to multiple ui objects works now! Thanks :)
